CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100),
  ability FLOAT DEFAULT 0,    -- θ
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE users 
ADD COLUMN email VARCHAR(255) UNIQUE,
ADD COLUMN password_hash VARCHAR(255),
ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;


ALTER TABLE users
ADD COLUMN is_verified TINYINT(1) DEFAULT 0 AFTER updated_at,
ADD COLUMN verification_token VARCHAR(255) NULL AFTER is_verified,
ADD COLUMN verification_token_expires DATETIME NULL AFTER verification_token;


ALTER TABLE users ADD COLUMN role VARCHAR(20) DEFAULT 'candidate';
